name: bigass metrics
on:
  schedule:
    - cron: "30 18 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: bottom
        uses: lowlighter/metrics@latest
        with:
          filename: bottom.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
#           config_order: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - name: lang
        uses: lowlighter/metrics@latest
        with:
          filename: lang.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 30
          plugin_languages_ignored: html, css, Smali
       
